Recommend System/6_Demo/SmartCity_WatershedMngt/urls.py
from django.conf.urls import url
from django.conf.urls import include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^watershed/',include('watershed.urls')),
    url(r'^yelp/',include('yelp.urls')),
]

Recommend System/6_Demo/watershed/urls.py
from django.conf.urls import patterns, url
from . import views

app_name = 'watershed'

urlpatterns = [



    #GenerateGeoRSS
    url(r'^GenerateGeoRSS$', views.GenerateGeoRSS, {'type':'GenerateGeoRSS'}, name='GenerateGeoRSS'),
    url(r'^goHome$', views.index, name='index'),
    url(r'^twentymindrive_map$', views.twentymindrive_map, {'type':'twentymindrive_map'}, name='twentymindrive_map'),
    url(r'^waterlevel_map$', views.waterlevel_map, {'type': 'waterlevel_map'}, name='waterlevel_map'),

    #URL for Generic Create
    url(r'^watershed_new$', views.generic_create, {'type':'Watershed'}, name='watershed_new'),
    url(r'^florafauna_new$', views.generic_create, {'type':'floraFauna'}, name='florafauna_new'),
    url(r'^maintenance_new$', views.generic_create, {'type':'Maintenance'}, name='maintenance_new'),
    url(r'^observation_new$', views.generic_create, {'type':'Observation'},name='observation_new'),
    url(r'^ffinfo_new$', views.generic_create, {'type':'ffinfo'}, name='ffinfo_new'),
    url(r'^naturalfeature_new$', views.generic_create, {'type':'Natural Feature'},name='naturalfeature_new'),
    url(r'^manmadefeature_new$', views.generic_create,{'type':'Manmade Feature'}, name='manmadefeature_new'),
    url(r'^wpconnection_new$', views.generic_create, {'type': 'WatershedPipeConnection'}, name='wpconnection_new'),

    #URL for Generic Update
    url(r'^wpconnection/(?P<pk>.*)/update$', views.generic_update, {'type':'WatershedPipeConnection'}, name='wpconnection_update'),
    url(r'^florafauna/(?P<pk>.*)/update$', views.generic_update, {'type':'floraFauna'},name='florafauna_update'),
    url(r'^maintenance/(?P<pk>.*)/update$', views.generic_update, {'type':'Maintenance'}, name='maintenance_update'),
    url(r'^observation/(?P<pk>.*)/update$', views.generic_update,{'type':'Observation'}, name='observation_update'),
    url(r'^ffinfo/(?P<pk>.*)/update$', views.generic_update, {'type':'ffinfo'},name='ffinfo_update'),
    url(r'^naturalfeature/(?P<pk>.*)/update$', views.generic_update, {'type':'Natural Feature'}, name='naturalfeature_update'),
    url(r'^manmadefeature/(?P<pk>.*)/update$', views.generic_update, {'type':'Manmade Feature'}, name='manmadefeature_update'),
    url(r'^(?P<pk>.*)/update$', views.generic_update, {'type':'Watershed'}, name='watershed_update'),


    #URL for Generic Delete
    url(r'^wpconnection/(?P<pk>.*)/delete$', views.generic_delete, {'type': 'WatershedPipeConnection'}, name='wpconnection_delete'),
    url(r'^manmadefeature/(?P<pk>.*)/delete$', views.generic_delete, {'type':'Manmade Feature'}, name='manmadefeature_delete'),
    url(r'^naturalfeature/(?P<pk>.*)/delete$', views.generic_delete, {'type':'Natural Feature'}, name='naturalfeature_delete'),
    url(r'^ffinfo/(?P<pk>.*)/delete$', views.generic_delete, {'type':'ffinfo'}, name='ffinfo_delete'),
    url(r'^observation/(?P<pk>.*)/delete$', views.generic_delete, {'type':'Observation'}, name='observation_delete'),
    url(r'^maintenance/(?P<pk>.*)/delete$', views.generic_delete, {'type':'Maintenance'}, name='maintenance_delete'),
    url(r'^florafauna/(?P<pk>.*)/delete$', views.generic_delete, {'type':'floraFauna'}, name='florafauna_delete'),
    url(r'^(?P<pk>.*)/delete$', views.generic_delete, {'type':'Watershed'}, name='watershed_delete'),

    #URL for Generic Read
    url(r'^maintenance/(?P<pk>.*)/$', views.generic_detail, {'type':'Maintenance'},name="detail_maintenance"),
    url(r'^florafauna/(?P<pk>.*)/$', views.generic_detail, {'type':'floraFauna'}, name="detail_florafauna"),
    url(r'^observation/(?P<pk>.*)/$', views.generic_detail,{'type':'Observation'}, name='detail_observation'),
    url(r'^ffinfo/(?P<pk>.*)/$', views.generic_detail, {'type':'ffinfo'},name='detail_ffinfo'),
    url(r'^naturalfeature/(?P<pk>.*)/$', views.generic_detail, {'type':'Natural Feature'}, name='detail_naturalfeature'),
    url(r'^manmadefeature/(?P<pk>.*)/$', views.generic_detail, {'type':'Manmade Feature'}, name='detail_manmadefeature'),
    url(r'^wpconnection/(?P<pk>.*)/$', views.generic_detail, {'type': 'WatershedPipeConnection'}, name='detail_wpconnection'),




    #URL for Generic Delete


    #URL for Maintenance
    #url(r'^maintenance/(?P<pk>.*)/update$', views.maintenance_update, name='maintenance_update'),
    #url(r'^maintenance/(?P<pk>.*)/delete$', views.maintenance_delete, name='maintenance_delete'),
    #url(r'^maintenance/(?P<pk>.*)/$', views.detail_maintenance, name="detail_maintenance"),
    #url(r'^maintenance_new$', views.maintenance_create, name='maintenance_new'),



    #URL for florafauna
    #url(r'^florafauna/(?P<pk>.*)/update$', views.florafauna_update, name='florafauna_update'),
    #url(r'^florafauna/(?P<pk>.*)/delete$', views.florafauna_delete, name='florafauna_delete'),
    #url(r'^florafauna/(?P<pk>.*)/$', views.detail_florafauna, name="detail_florafauna"),
    #url(r'^florafauna_new$', views.florafauna_create, name='florafauna_new'),
    
    #URL for homepage
    url(r'^$', views.index, name="index"),

    
    #URL for Watershed
    url(r'^(?P<pk>.*)/$',views.generic_detail, {'type':'Watershed'}, name="detail"),
    # url(r'^(?P<watershed_id>[0-9]+)/$', views.detail, name="detail"),
    #url(r'^watershed_view/(?P<pk>\d+)$', views.watershed_view, name='watershed_view'),
    #url(r'^watershed_new$', views.watershed_create, name='watershed_new'),
    #url(r'^(?P<pk>.*)/update$', views.watershed_update, name='watershed_update'),
    #url(r'^(?P<pk>.*)/delete$', views.watershed_delete, name='watershed_delete'),
]

Recommend System/6_Demo/yelp/urls.py
from django.conf.urls import url
from django.conf.urls import include
from django.contrib import admin
from yelp import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name="index"),
    url(r'^map$', views.googlemap, name='googlemap'),
    url(r'^(?P<pk>.*)/$',views.detail, name="detail"),
]

Recommend System/6_Demo/watershed/views.py
from django.http import HttpResponse, Http404
from watershed.models import *
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.shortcuts import render, redirect, get_object_or_404
from django.forms import ModelForm
from django.core.exceptions import ObjectDoesNotExist
from watershed.forms import *
from django.http import Http404


# #Generate GeoRSS
# def GeoRSS

def twentymindrive_map(request, type):
    template_name = 'watershed/twentymindrive_map.html'
    return render(request, template_name)

def waterlevel_map(request, type):
    template_name = 'watershed/waterlevel_map.html'
    return render(request, template_name)

def GenerateGeoRSS(request, type):
    # GeoRssGenerator()
    #Load form
    template_name='watershed/index.html'
    return index(request)



# ======== Generic CRUD ======

#CREATE
def generic_create(request, type):
    #Identify the type of form
    ctx={}
    ctx["type"] = type

    if type == 'Watershed':
        form = WatershedForm(request.POST or None)
    elif type == 'floraFauna':
        form = FloraFaunaForm(request.POST or None)
        ctx['type'] = 'Flora and Fauna'
    elif type == 'Maintenance':
        form = MaintenanceForm(request.POST or None)
    elif type == 'Observation':
        form = ObservationForm(request.POST or None)
    elif type == 'Natural Feature':
        form = NaturalFeatureForm(request.POST or None)
    elif type == 'Manmade Feature':
        form = ManmadeFeatureForm(request.POST or None)
    elif type == 'ffinfo':
        form = ffInfoForm(request.POST or None)
        ctx['type'] = 'Flora and Fauna Specifics'
    elif type == 'WatershedPipeConnection':
        form = WatershedPipeForm(request.POST or None)
        ctx['type']='Watershed - Pipe Connection'

    else:
        form = None

    #Load form
    if form.is_valid():
        form.save()
        return redirect('watershed:index')
    ctx["form"] = form
  
    template_name='watershed/generic_form.html'
    return render(request, template_name, ctx)

#UPDATE
def generic_update(request, pk, type):
    #Identify the type of form
    ctx = {}
    if type == 'Watershed':
        watershed = get_object_or_404(Watershed, pk=pk)
        form = WatershedForm(request.POST or None, instance=watershed)
        form.fields['watershedID'].widget.attrs['readonly'] = True

    elif type == 'floraFauna':
        flora = get_object_or_404(FloraFauna, pk=pk)
        form = FloraFaunaForm(request.POST or None, instance=flora)
        ctx['type'] = 'Flora and Fauna'
        form.fields['florafaunaID'].widget.attrs['readonly'] = True

    elif type == 'Maintenance':
        maintenance = get_object_or_404(Maintenance, pk=pk)
        form=MaintenanceForm(request.POST or None, instance=maintenance)
        form.fields['watershedID'].widget.attrs['readonly'] = True
        form.fields['maintenanceID'].widget.attrs['readonly'] = True

    elif type == 'Observation':
        observation = get_object_or_404(Observation, pk=pk)
        form = ObservationForm(request.POST or None, instance=observation)
        form.fields['watershedID'].widget.attrs['readonly'] = True
        form.fields['observationID'].widget.attrs['readonly'] = True

    elif type == 'Natural Feature':
        naturalFeature = get_object_or_404(NaturalFeature, pk=pk)
        form = NaturalFeatureForm(request.POST or None, instance=naturalFeature)
        form.fields['watershedID'].widget.attrs['readonly'] = True
        form.fields['featureID'].widget.attrs['readonly'] = True


    elif type == 'Manmade Feature':
        manMadeFeature = get_object_or_404(ManmadeFeature, pk=pk)
        form = ManmadeFeatureForm(request.POST or None, instance=manMadeFeature)
        form.fields['watershedID'].widget.attrs['readonly'] = True
        form.fields['featureID'].widget.attrs['readonly'] = True

    elif type == 'ffinfo':
        ffInfoInstance=get_object_or_404(ffInfo, pk=pk)
        form = ffInfoForm(request.POST or None, instance=ffInfoInstance)
        ctx['type'] = 'Flora and Fauna Specifics'
        form.fields['watershedID'].widget.attrs['readonly'] = True
        form.fields['florafaunaID'].widget.attrs['readonly'] = True
        form.fields['ffInfoID'].widget.attrs['readonly'] = True

    elif type == 'WatershedPipeConnection':
        wpconnection =get_object_or_404(WatershedPipe, pk=pk)
        form = WatershedPipeForm(request.POST or None, instance= wpconnection)
        ctx['type']='Watershed - Pipe Connection'

    else:
        form = None

    #Load form
    if form.is_valid():
        form.save()
        return redirect('watershed:index')
    
    ctx["form"] = form
    ctx['type'] = type
    template_name='watershed/generic_form.html'
    return render(request, template_name, ctx)

#READ
def generic_detail(request, pk, type):
    ctx={}
    ctx['type']=type
    ctx['pk']=pk
    ctx['Add']=''
    ctx['Delete']=''
    ctx['update']=''
    template_name='watershed/generic_detail.html'

    if type == 'Watershed':
        watershed = get_object_or_404(Watershed, pk=pk)
        try:
            maintenance = Maintenance.objects.all().filter(watershedID=pk)
        except ObjectDoesNotExist:
            maintenance = None
        try:
            manMadeFeatures = ManmadeFeature.objects.all().filter(watershedID=pk)
        except ObjectDoesNotExist:
            manMadeFeatures = None
        try:
            naturalFeatures = NaturalFeature.objects.all().filter(watershedID=pk)
        except ObjectDoesNotExist:
            naturalFeatures = None
        try:
            observationV = Observation.objects.all().filter(watershedID=pk)
        except ObjectDoesNotExist:
            observationV = None
        try:
            FloraAndFauna = ffInfo.objects.all().filter(watershedID=pk)
        except ObjectDoesNotExist:
            FloraAndFauna = None
        try:
            WPConnection = WatershedPipe.objects.all().filter(watershedID=pk)
        except ObjectDoesNotExist:
            WPConnection = None

        ctx['watershed']=watershed
        ctx['maintenance']=maintenance
        ctx['manMadeFeatures']=manMadeFeatures
        ctx['naturalFeatures']=naturalFeatures
        ctx['observationV']=observationV
        ctx['FloraAndFauna']=FloraAndFauna
        ctx['WPConnection'] = WPConnection
        template_name='watershed/detail.html'

    elif type == 'floraFauna':
        florafauna = get_object_or_404(FloraFauna, pk=pk)
        ctx['entity']=florafauna
        ctx['Add']='watershed:florafauna_new'
        ctx['Delete']='watershed:florafauna_delete'
        ctx['Update']='watershed:florafauna_update'
        ctx['type'] = 'Flora and Fauna'

    elif type == 'Maintenance':
        maintenance = get_object_or_404(Maintenance, pk=pk)
        ctx['entity']=maintenance
        ctx['Add']='watershed:maintenance_new'
        ctx['Delete']='watershed:maintenance_delete'
        ctx['Update']='watershed:maintenance_update'

    elif type == 'Observation':
        obs=get_object_or_404(Observation, pk=pk)
        ctx['entity']=obs
        ctx['Add']='watershed:observation_new'
        ctx['Delete']='watershed:observation_delete'
        ctx['Update']='watershed:observation_update'

    elif type == 'Natural Feature':
        natF=get_object_or_404(NaturalFeature, pk=pk)
        ctx['entity']=natF
        ctx['Add']='watershed:naturalfeature_new'
        ctx['Delete']='watershed:naturalfeature_delete'
        ctx['Update']='watershed:naturalfeature_update'


    elif type == 'Manmade Feature':
        manmade=get_object_or_404(ManmadeFeature, pk=pk)
        ctx['entity']=manmade
        ctx['Add']='watershed:manmadefeature_new'
        ctx['Delete']='watershed:manmadefeature_delete'
        ctx['Update']='watershed:manmadefeature_update'

    elif type == 'ffinfo':
        ffInfoV=get_object_or_404(ffInfo, pk=pk)
        ctx['entity']=ffInfoV
        ctx['Add']='watershed:ffinfo_new'
        ctx['Delete']='watershed:ffinfo_delete'
        ctx['Update']='watershed:ffinfo_update'
        ctx['type'] = 'Flora and Fauna Specifics'

    elif type == 'WatershedPipeConnection':
        wpc=get_object_or_404(WatershedPipe, pk=pk)
        ctx['entity']=wpc
        ctx['Add']='watershed:wpconnection_new'
        ctx['Delete']='watershed:wpconnection_delete'
        ctx['Update']='watershed:wpconnection_update'
        ctx['type']='Watershed - Pipe Connection'

    else:
        form = None

    #Load form
    return render(request, template_name, ctx)

#DELETE
def generic_delete(request, pk, type):
    if type == 'Watershed':
        Watershed.objects.filter(watershedID=pk).delete()
    elif type == 'floraFauna':
        FloraFauna.objects.filter(florafaunaID=pk).delete()
    elif type == 'Maintenance':
        Maintenance.objects.filter(maintenanceID=pk).delete()
    elif type == 'Observation':
        Observation.objects.filter(observationID=pk).delete()
    elif type == 'Natural Feature':
        NaturalFeature.objects.filter(featureID=pk).delete()
    elif type == 'Manmade Feature':
        ManmadeFeature.objects.filter(featureID=pk).delete()
    elif type == 'ffinfo':
        ffInfo.objects.filter(ffInfoID=pk).delete()
    elif type == 'WatershedPipeConnection':
        WatershedPipe.objects.filter(connectionID=pk).delete()
    else:
        pass

    #Load form
    template_name='watershed/index.html'
    return index(request) 



# ========== Home =========

def index(request):



    all_watershed = Watershed.objects.all()
    all_florafauna = FloraFauna.objects.all()
    all_maintenance = Maintenance.objects.all()
    all_manmadefeature = ManmadeFeature.objects.all()
    all_naturalfeature = NaturalFeature.objects.all()
    all_ffinfo = ffInfo.objects.all()
    all_observation = Observation.objects.all()
    all_watershedpipe = WatershedPipe.objects.all()

    context = {
        'all_watershed': all_watershed,
        'all_florafauna': all_florafauna,
        'all_maintenance': all_maintenance,

Recommend System/6_Demo/watershed/templates/watershed/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>index</title>
    <!-- Bootstrap -->
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static "customCSS.css" %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>

<body>

<!-- NAVIGATION -->
<nav class="navbar navbar-default navbar-fixed-top customNavBar">
    <div class="container-fluid">
        <p class="navbar-text customNavBarLink"><a href="{% url 'watershed:GenerateGeoRSS' %}" class="navbar-link"> Home</a></p>

        <p class="navbar-text customNavBarLink"><a href="{% url 'watershed:twentymindrive_map' %}" class="navbar-link">20-Min-Travel</a></p>
        staMaintainance Service</a></p>
        <p class="navbar-text navbar-right customNavBarLink">
            <a class="navbar-link  " href="http://smartcities.mbrxdram5u.us-west-2.elasticbeanstalk.com/waterevent/"> Stormwater System</a></p>
  </div>
</nav>

<div class="jumbotron text-center">
        <h1>Watershed Management System</h1>
        
        
</div>

<!--
<a href="{% url 'watershed:GenerateGeoRSS' %}" class="btn btn-primary btn-sm active btn-block text-center" role="button" aria-pressed="true"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span>Generate GeoRSS</a>
<br>
-->

<div class="container-fluid">

    <!-- Group of buttons -->
    <div class="btn-group btn-group-justified" role="group" aria-label="...">
        <a href="{% url 'watershed:watershed_new' %}" class="btn btn-primary btn-md active btn-block text-center" role="button" aria-pressed="true"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Watershed</a>
        <a href="{% url 'watershed:wpconnection_new' %}" class="btn btn-primary btn-md active btn-block text-center" role="button" aria-pressed="true"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span>  Watershed-Pipe Connection </a>
    </div>
    
    <div class="btn-group btn-group-justified" role="group" aria-label="...">
        <a href="{% url 'watershed:florafauna_new' %}" class="btn btn-info btn-md active text-center" role="button" aria-pressed="true"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span>  Flora and Fauna</a>
        <a href="{% url 'watershed:maintenance_new' %}" class="btn btn-info btn-md active text-center" role="button" aria-pressed="true"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span>  Maintenance</a>

        <div class="btn-group" role="group">
            <button type="button" class="btn btn-info active dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
      Features
      <span class="caret"></span>
            </button>
                <ul class="dropdown-menu">
                    <li><a href="{% url 'watershed:manmadefeature_new' %}">Man made</a></li>
                    <li><a href="{% url 'watershed:naturalfeature_new' %}">Natural</a></li>
                </ul>
        </div>
       
        <a href="{% url 'watershed:ffinfo_new' %}" class="btn btn-info btn-md active text-center" role="button" aria-pressed="true"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Flora Fauna Info</a>
        <a href="{% url 'watershed:observation_new' %}" class="btn btn-info btn-md active text-center" role="button" aria-pressed="true"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span>  Observation</a>
        
    </div>
    <br>



    <!--Watershed List-->
   <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
      <h3 class="page-header">Watershed List:</h3>
      <em>Click on the name to see more details</em>
        {% if all_watershed %}
        <div class="list-group">
            {% for watershed in all_watershed %}
            <div class="list-group-item">
                <a href="{% url 'watershed:detail' watershed.watershedID %}" class="h4">{{ watershed.name }}</a>
                
                <span class="pull-right">
                    <a class="btn btn-xs btn-warning" href="{% url 'watershed:watershed_update' watershed.watershedID %}">
                        <span class="glyphicon glyphicon-pencil"></span>
                    </a>
                    <a class="btn btn-xs btn-danger" href="{% url 'watershed:watershed_delete' watershed.watershedID %}">
                        <span class="glyphicon glyphicon-trash"></span>
                    </a>
                </span>  
            </div>
            {% endfor %}
        </div>
         {% else %}
            <em> You have no watersheds in your database </em>
        {% endif %}
    </div>

    <!--Flora and fauna List-->
    <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
        <h3 class="page-header">Flora & Fauna List:</h3>
        <em>Click on the name to see more details</em>
    {% if all_florafauna %}
    <div class="list-group">
        {% for florafauna in all_florafauna %}
        <div class="list-group-item">
            <a href="{% url 'watershed:detail_florafauna' florafauna.florafaunaID %}" class="h4">{{ florafauna.name }}</a>

            <span class="pull-right">
                <a class="btn btn-xs btn-warning" href="{% url 'watershed:florafauna_update' florafauna.florafaunaID %}">
                    <span class="glyphicon glyphicon-pencil"></span>
                </a>
                <a class="btn btn-xs btn-danger" href="{% url 'watershed:florafauna_delete' florafauna.florafaunaID %}">
                    <span class="glyphicon glyphicon-trash"></span>
                </a>
            </span>


        </div>
        {% endfor %}
    </div>
     {% else %}
        <em> You have no florafaunas in your database </em>
    {% endif %}
    </div>

    <!-- Connections-->
    <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
        <h3 class="page-header">Connection Information:</h3>
        <em>Click on the name to see more details</em>
        {% if all_watershedpipe %}
        <div class="list-group">
            {% for info in all_watershedpipe %}
            <div class="list-group-item">
                <a href="{% url 'watershed:detail_wpconnection' info.connectionID %}" class="h4">{{ info.connectionID }}</a>

                <span class="pull-right">
                    <a class="btn btn-xs btn-warning" href="{% url 'watershed:wpconnection_update' info.connectionID %}">
                        <span class="glyphicon glyphicon-pencil"></span>
                    </a>
                    <a class="btn btn-xs btn-danger" href="{% url 'watershed:wpconnection_delete' info.connectionID %}">
                        <span class="glyphicon glyphicon-trash"></span>
                    </a>
                </span>

            </div>
            {% endfor %}
        </div>
         {% else %}
            <em> You have no Watershed-Pipe connection Information in your database </em>
        {% endif %}
        
    </div>


</div>




    <!-- FOOTER -->
    <footer>
      <div class="container">
          <div class="col-md-6 col-sm-6 footerleft ">
            <div class="title-footer text-center"> About the Project</div>
            <p>This web application was made as part of the class Business Process Analysis, taught at the University of Maryland - Smith School of Business. It is the final project and served as a learning platform for the students to test and understand the different technologies. </p>
            <p>Through out the project, we learned the agile methodology and did a total of 6 sprints. Some of the techonologies and tools used in this app include Django, Python, ArcGis, Amazon AWS and Bootstrap .</p>


          </div>
          <div class="col-md-6 col-sm-6 paddingtop-bottom text-center">
            <h6 class="title-footer">About us</h6>
            <ul class="footer-ul text-center">
              <li><a href="https://www.linkedin.com/in/amiyakumardas/"> Amiya Das<br/> <i class="fa fa-linkedin-square" style="font-size:24px"></i></a></li>
              <li><a href="https://www.linkedin.com/in/melissa-delcid-94380a8b/"> Melissa Delcid<br> <i class="fa fa-linkedin-square" style="font-size:24px"></i></a></li>
              <li><a href="https://www.linkedin.com/in/kanchan-markandeya-041ba1b5/"> Kanchan Markandeya<br/><i class="fa fa-linkedin-square" style="font-size:24px"></i></a></li>
              <li><a href="https://www.linkedin.com/in/yangmen/">Yang Men<br/><i class="fa fa-linkedin-square" style="font-size:24px"></i></a></li>
              <li><a href="https://www.linkedin.com/in/zheng-gong-78396777/">Zheng Gong<br/><i class="fa fa-linkedin-square" style="font-size:24px"></i></a></li>
              <li><a href="https://www.linkedin.com/in/gonche1124/"> Andres Gonzalez<br/><i class="fa fa-linkedin-square" style="font-size:24px"></i></a></li>
            </ul>
          </div>
      </div>
    </footer>




</body>
</html>

Recommend System/6_Demo/watershed/templates/watershed/watershed_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Delete</title>
    <!-- Bootstrap -->
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<h1>Your record is deleted.</h1>


</body>
</html>